import { IndexPageData, SponsorCategory } from '@/models/models';

export const conferenceData: IndexPageData = {
  previousConferences: {
    sectionTitle: 'Korábbi Konferenciák',
    conferences: [
      {
        title: 'XX. Simonyi Konferencia',
        priority: 2023,
        imageUrls: [
          '/img/235_1LO0J6H1906X6.jpg',
          '/img/230_ZRJV0PK2DB7P.jpg',
          '/img/231_11QP9ARXVT6QR.jpg',
          '/img/232_RXOCJ2USV36H.jpg',
          '/img/233_MOU6L631ZXM7.jpg',
          '/img/234_1O2U1VBZ9ZZ4G.jpg',
        ],
      },
      {
        title: 'XIX. Simonyi Konferencia',
        priority: 2022,
        imageUrls: [
          '/img/220_1XISYXMRTE7YK.jpg',
          '/img/221_17BTXE6MX5HJ9.jpg',
          '/img/222_3ECBM0ZFB1K9.jpg',
          '/img/223_1GWWX2XNMQD6M.jpg',
          '/img/224_R475DKI1KNSM.jpg',
        ],
      },
      {
        title: '18. Simonyi konferencia',
        priority: 2021,
        imageUrls: [
          '/img/210_OERS7G9S2NL2.jpg',
          '/img/211_1LBTT8EB48NZJ.jpg',
          '/img/212_QZQUP5HUPYCU.jpg',
          '/img/213_1RK2FGBGE995R.jpg',
          '/img/214_1U6FHC3PT163A.jpg',
        ],
      },
      {
        title: 'XVI. Simonyi Konferencia',
        priority: 2019,
        imageUrls: [
          '/img/192_K954WUW5ZXJA.jpg',
          '/img/190_196F9RYZQ11ZL.jpg',
          '/img/191_L8ZNRT0SFIH9.jpg',
          '/img/193_1F7ODC8Y7G5CF.jpg',
          '/img/194_1TMQA608OEYB5.jpg',
        ],
      },
      {
        title: 'XV. Simonyi Konferencia',
        priority: 2018,
        imageUrls: [
          '/img/180_OU6NPGLX7UIR.jpg',
          '/img/181_ZJ51F7928IB8.jpg',
          '/img/182_7U2UI2JV2XYE.jpg',
          '/img/183_W3W4PY1CYFJA.jpg',
          '/img/184_1T3T7C7LRNL9.jpg',
          '/img/185_R0G344T97PHV.jpg',
        ],
      },
      {
        title: 'XIV. Simonyi Konferencia',
        priority: 2017,
        imageUrls: [
          '/img/170_1NCMIE7YZOGQT.jpg',
          '/img/171_V5CT6VBYFABN.jpg',
          '/img/172_19R3YW32UCIM7.jpg',
          '/img/173_10G8GH2CEB5DB.jpg',
          '/img/174_QTJDIDGIEK05.jpg',
          '/img/175_1FC3AW360LKHE.jpg',
        ],
      },
      {
        title: 'XIII. Simonyi Konferencia',
        priority: 2016,
        imageUrls: [
          '/img/161_1USY0RQFNB7LD.jpg',
          '/img/160_DCX0E01VVYUO.jpg',
          '/img/162_1X70T76ISRH3O.jpg',
          '/img/163_12SB4BAIHTHQ2.jpg',
          '/img/164_1476NFGMHZ95U.jpg',
        ],
      },
      {
        title: 'XII. Simonyi Konferencia',
        priority: 2015,
        imageUrls: [
          '/img/150_15NNNI8N8FC7X.jpg',
          '/img/151_12WHAHMNSOHSC.jpg',
          '/img/152_1PSSOQGR2K7SL.jpg',
          '/img/153_EFVJWIL2W613.jpg',
          '/img/154_YIORMCI4X8CA.jpg',
        ],
      },
      {
        title: 'XI. Simonyi Konferencia',
        priority: 2014,
        imageUrls: [
          '/img/142_128VXAYYEVOWX.jpg',
          '/img/140_GVLBCNPR8XCL.jpg',
          '/img/143_MPN2YLF5F27I.jpg',
          '/img/144_1KWM4FV2R8PE5.jpg',
        ],
      },
    ],
  },
  registration: { buttonText: 'Regisztráció', cooltixEventId: '6571022a69d7b459070e41e4' },
  mobilApp: {
    description: 'Regisztráció',
    androidUrl: 'https://kir-dev.hu/ly/konferenciappandroid',
    iosUrl: 'https://kir-dev.hu/ly/konferenciappios',
  },
  giveaway: {
    sectionTitle: 'Nyereményjáték',
    description:
      'A regisztrált résztvevők között az esemény végén kisorsolunk egy ***Nintendo Switch OLED Model*** hordozható játékkonzolt.',
    pictureUrl: '/img/SWITCH_104098T2KYXI3.webp',
    rules:
      '# Nyereményjáték-szabályzat\r\n\r\nA Nyereményjáték-szabályzat (a továbbiakban: **Szabályzat**) vonatkozik a Simonyi Károly Szakkollégium (továbbiakban: **Szakkollégium**) által szervezett XXI. Simonyi Konferencia (továbbiakban: **Esemény**) során folyó nyereményjátékokra (továbbiakban: **Játék**).\r\n\r\nA Szakkollégium elérhetőségei:\r\n\r\n- 1117 Budapest, Irinyi József utca 42. Schönherz Kollégium 1320-as szoba\r\n- [info@simonyi.bme.hu](mailto:info@simonyi.bme.hu)\r\n\r\nAz Esemény helyszíne:\r\n\r\n- Budapesti Műszaki és Gazdaságtudományi Egyetem Villamosmérnöki és Informatikai Karának I épülete (1117 Budapest, Magyar Tudósok Körútja 2.) (továbbiakban: **Egyetem** ).\r\n\r\n## 1. A Játékban részt vevő személyek\r\n\r\nA Játékban részt vehet minden természetes személy, aki regisztrált az Eseményre a [konferencia Cooltix](https://cooltix.com/widget/event-products/6571022a69d7b459070e41e4) oldalán.\r\n\r\nA Játékban **NEM vehetnek részt** az alábbi személyek:\r\n\r\n- A Szakkollégium Elnökségének, Szervezeti Bizottságának és Felügyelő Bizottságának tagjai.\r\n- A rendezvény alatt munkát végző technikai stáb tagjai, vagy lebonyolításban segédkező személyek.\r\n- Az Esemény szervezői, meghívott előadói és standolói; egyéb, a lebonyolításban közvetlenül közreműködő cégek tulajdonosai, vezető tisztségviselői, munkavállalói, megbízottjai, valamint azok közeli hozzátartozói.\r\n\r\n## 2. A Játék leírása\r\n\r\nAz Eseményhez köthető általános nyereményjáték során a Játékos érvényes regisztrációval rendelkezik és leadta jelentkezését az Esemény regisztrációs pultjánál.\r\n\r\n## 3. A Játék időtartama\r\n\r\nA Játék 2024. március 19. 12:00 és 2024. március 19. 18:00 között tart.\r\n\r\n## 4. Jelentkezés a Játékra\r\n\r\nA Játékra jelentkezni 2024. március 19. 12:00 és 18:00 között van lehetőség a Konferencia regisztrációs pultjánál.\r\n\r\nEgy Játékos mind a négy nyereményjátékban csak egyszer vehet részt.\r\n\r\nA nyeremények átvételéhez szükséges lehet a pontos név, személyi igazolvány szám és lakcím megadása.\r\n\r\n_A Játékos a nyereményjátékban való részvételével elfogadja a Nyereményjáték-szabályzatot és a szabályzatban foglaltak szerint hozzájárult személyes adatai kezeléséhez._\r\n\r\n## 5. Nyeremény\r\n\r\nA Játékban megnyerhető nyeremények:\r\n\r\n- 3 db 15 000 Forint értékű Media Markt utalvány\r\n- 1 db 140 000 Ft értékű Nintendo Switch OLED játékkonzol \r\n\r\nAmennyiben a nyeremény átvételének időpontjában nem áll rendelkezésre a megjelölt termék, akkor ahhoz értékben hasonló ajándéktárgy kerül átadásra.\r\n\r\n**A nyeremények más részére át nem ruházhatók és pénzre át nem válthatók.**\r\n\r\nA Szakkollégium vállalja, hogy kifizeti a nyereményre esetlegesen közvetlenül alkalmazandó személyi jövedelemadót, illetve vállalja a nyereményekkel kapcsolatban közvetlenül felmerülő további adó vagy egyéb esetleges járulék megfizetését.\r\n\r\n## 6. Sorsolás\r\n\r\nA videó felvétellel rögzített sorsolásra 2024. év március hó 19. napján 19:30-kor kerül sor az Egyetem IB028-as előadótermében.\r\n\r\nAz Esemény során történő nyereményjáték sorsolását az Esemény szervezőiből álló sorsolási bizottság végzi.\r\n\r\n## 7. A sorsolás lebonyolítása\r\n\r\nA sorsolás kamera előtt, videofelvétel rögzítésével történik.\r\n\r\nA 4 darab nyereményt 4 különböző játékos nyerheti meg, ezért a sorsolások folyamán a már kisorsolt játékosok a sorsolás további részében nem sorsolhatók ki újra.\r\n\r\nAmennyiben a nyertes nem tartózkodik a helyszínen úgy új nyertes kerül kisorsolásra.\r\n\r\nA sorsolás addig tart, amíg a nyeremények nyertesei kisorsolásra kerülnek, és ennek megfelelően a sorsolás egyfordulós.\r\n\r\n## 8. A nyeremények átvétele\r\n\r\nA nyerteseket minden esetben személyesen értesítjük 2024. 03. 19. 19:30 és 20:00 között az Egyetem IB028-as előadójában.\r\n\r\nA nyereménytárgyak átvételére kizárólag az Eseményen van lehetőség 2024. 03. 19. 19:30 és 20:00 között.\r\n\r\nAz átvétellel kapcsolatos reklamáció kizárólag a Szakkollégiumnál tehető meg.\r\n\r\nA Játékosok kötelesek együttműködni a nyeremények átvétele/igénybevétele érdekében. Amennyiben ennek nem tesznek eleget, és a nyeremény átvétele meghiúsul, a nyeremény a továbbiakban nem vehető át, illetve nem vehető igénybe. A Szakkollégiumot semmilyen felelősség nem terheli.\r\n\r\n## 9. Adatkezelés\r\n\r\nA _Játékosok_ a Játékban való részvétellel automatikusan hozzájárulnak ahhoz, hogy\r\n\r\n- megadott adataik (név, lakcím, személyi igazolvány szám) a Szakkollégium, mint adatkezelő adatbázisába kerüljenek, és azokat a Szakkollégium minden további engedély, illetve ellenszolgáltatás nélkül kezelje a nyeremények kisorsolása, a nyertesek értesítése és a sorsolásig érkező reklamációk kezelése céljából, legfeljebb a sorsolást követő 6 hónapig.\r\n\r\nAz adatkezelő által használt adatok vonatkozásában a Játékost megilleti a személyes adatok védelméről és a közérdekű adatok nyilvánosságáról szóló 1992. évi LXIII. törvény (Adatvédelmi törvény) 11-16/A. §-aiban meghatározott valamennyi jogosultság, esetleges jogérvényesítési igényét pedig bíróság előtt gyakorolhatja, valamint kérheti az adatvédelmi biztos segítségét is.\r\n\r\nA Szakkollégium a személyes adatokat az Adatvédelmi törvény rendelkezései szerint, bizalmasan kezeli a Játékosoktól kapott felhatalmazások keretei között.\r\n\r\n## 10. Felelősségkizárás\r\n\r\nA pályázatok hiányosságáért (névelírás stb.) értesítési, vagy átvételi késedelemért a Szakkollégium nem vállal felelősséget. A Játékosok az általuk tévesen szolgáltatott adatokból adódó valamennyi következményt maguk viselik. Az adatok helytállóságát a Játékra történő jelentkezés során (vagy azt követően) a Szakkollégiumnak nem áll módjában ellenőrizni. Ezzel kapcsolatban a felelősség és minden ezzel járó jogi és anyagi következmény minden esetben a Játékosokat terheli.\r\n\r\n## 11. Egyéb\r\n\r\nA Játékos a Játékban történő részvétellel automatikusan elfogadja a jelen Szabályzatot és feltétel nélküli beleegyezését adja ahhoz, hogy nyertessége esetén nevét és fényképét a Konferencia weboldalán, Facebook- valamint Instagram-oldalán a sorsolástól számított 6 hónapig nyilvánosságra hozza. A Játékos a fénykép beküldésével szavatolja, hogy amennyiben a fényképen a Játékoson kívül más is szerepel, vagy a fénykép közzététele egyéb okból harmadik személy hozzájárulásához kötött, rendelkezik e személyek közzétételhez való hozzájárulásával. A Játékos kijelenti, hogy a regisztrációs adatai megfelelnek a valóságnak.',
  },
  promoVideo: {
    sectionTitle: 'Mi is az a Simonyi Konferencia?',
    youtubeUrl: 'https://www.youtube.com/embed/xxxxxx',
    description:
      'A Simonyi Károly Szakkollégium évente megrendezésre kerülő nagyrendezvénye. A konferencia izgalmas pillanatokat kínál mindazoknak, akik érdeklődnek a mérnöki és informatikai területek legfrissebb fejlesztései iránt. Szánj egy pillantást korábbi rendezvényeink hangulatára, és tekintsd át az előző konferenciák életképeit és tarts velünk 2024-ben is!',
  },
  sponsors: {
    sectionTitle: 'Szponzoraink',
    companies: [
      {
        name: 'Bosch',
        logoUrl: '/img/BOSCHNOTEXT_1R741C5F9QCN3.svg',
        url: 'https://www.bosch.hu/karrier/?gad_source=1',
        category: SponsorCategory.MAIN_SPONSOR,
      },
      {
        name: 'Barré Technologies',
        logoUrl: '/img/BARRE_176COXBUV467Q.svg',
        url: 'https://www.barre.hu/',
        category: SponsorCategory.FEATURED_SPONSOR,
      },
      {
        name: 'Sicontact',
        logoUrl: '/img/SICONTACT_15M63HYJWCCDV.svg',
        url: 'https://www.eset.com/hu/',
        category: SponsorCategory.FEATURED_SPONSOR,
      },
      {
        name: 'Interactive Brokers',
        logoUrl: '/img/IB_W4TUT1GY25YU.svg',
        url: 'https://www.interactivebrokers.hu/hu/home.php',
        category: SponsorCategory.FEATURED_SPONSOR,
      },
      {
        name: 'BME-VIK',
        logoUrl: '/img/VIK_8K0EV31F2NVV.svg',
        url: 'https://vik.bme.hu/',
        category: SponsorCategory.FEATURED_SPONSOR,
      },
      {
        name: 'ICF Tech',
        logoUrl: '/img/ICF_ZNY49IVDX4WM.svg',
        url: 'https://careers.icftech.hu/',
        category: SponsorCategory.FEATURED_SPONSOR,
      },
      {
        name: 'Silicon Labs',
        logoUrl: '/img/SL_Y5X1DBHXY670.svg',
        url: 'https://www.silabs.com/about-us/careers?p=jobs&nl=1',
        category: SponsorCategory.FEATURED_SPONSOR,
      },
      {
        name: 'OTP Bank',
        logoUrl: '/img/OTP_RI4G0842GB45.svg',
        url: 'https://www.otpbank.hu/',
        category: SponsorCategory.FEATURED_SPONSOR,
      },
      {
        name: 'Nokia',
        logoUrl: '/img/NOKIA_168XXPH2NWTJG.svg',
        url: 'https://www.facebook.com/nokiahungary/',
        category: SponsorCategory.FEATURED_SPONSOR,
      },
      {
        name: 'Paks II',
        logoUrl: '/img/PAKS_1AOTVUGR60W1P.svg',
        url: 'https://www.paks2.hu/',
        category: SponsorCategory.SPONSOR,
      },
      {
        name: 'Nova Services',
        logoUrl: '/img/NOVA_1AAFIOWM3I4XE.png',
        url: 'https://www.novaservices.hu/',
        category: SponsorCategory.SPONSOR,
      },
      {
        name: 'KUKA',
        logoUrl: '/img/KUKA_17FAAFFKFQXAN.svg',
        url: 'https://www.kuka.com/hu-hu',
        category: SponsorCategory.SPONSOR,
      },
      {
        name: 'Knorr-Bremse',
        logoUrl: '/img/KB_YM32X3WEQYVY.svg',
        url: 'https://www.knorr-bremse.hu/hu/',
        category: SponsorCategory.SPONSOR,
      },
      {
        name: 'Schönherz',
        logoUrl: '/img/SCH_ZQ0NBYDERCDV.svg',
        url: '',
        category: SponsorCategory.SPONSOR,
      },
      {
        name: 'SVK',
        logoUrl: '/img/SVK_QB2UQ5W5MC8O.svg',
        url: '',
        category: SponsorCategory.SPONSOR,
      },
      {
        name: '4iG',
        logoUrl: '/img/4IG_TQNCRLDIT5O7.svg',
        url: 'https://4ig.hu/nyito',
        category: SponsorCategory.FEATURED_SPONSOR,
      },
      {
        name: 'Antenna Hungária',
        logoUrl: '/img/AH_19QI0DTGMIDR.svg',
        url: 'https://www.ahrt.hu/',
        category: SponsorCategory.SPONSOR,
      },
    ],
  },
  organisers: [
    {
      name: 'Piller Trisztán',
      rank: 'főrendező',
      emailAddress: 'piller.trisztan@simonyi.bme.hu',
      pictureUrl: '/img/TRISZ_GN68MH1S4AGK.webp',
      priority: 0,
    },
    {
      name: 'Kiss Mária Dominika',
      rank: 'PR- és sajtófelelős',
      emailAddress: 'kiss.maria.dominika@simonyi.bme.hu',
      pictureUrl: '/img/MARI_1DVGNYNN55903.webp',
      priority: 0,
    },
    {
      name: 'Técsi Zsuzsanna Vilma',
      rank: 'Szakkollégium elnöke',
      emailAddress: 'tecsi.zsuzsanna.vilma@simonyi.bme.hu',
      pictureUrl: '/img/TZSV_OM2JS1Q2PCE2.webp',
      priority: 0,
    },
    {
      name: 'Sághi Virág',
      rank: 'arculati felelős',
      emailAddress: 'saghi.virag@simonyi.bme.hu',
      pictureUrl: '/img/VIRAG_M97F94SD73CT.webp',
      priority: 1,
    },
    {
      name: 'Fekete Sámuel',
      rank: 'webfelelős',
      emailAddress: 'fekete.samuel@simonyi.bme.hu',
      pictureUrl: '/img/SAMU_QEFOM7FENEIZ.webp',
      priority: 1,
    },
    {
      name: 'Berente Bálint István',
      rank: 'KonferenciApp felelőse',
      emailAddress: 'berente.balint@simonyi.bme.hu',
      pictureUrl: '/img/BB_1VT0LTSCVH2P6.webp',
      priority: 1,
    },
    {
      name: 'Dániel Miklós',
      rank: 'webdesign felelőse',
      emailAddress: 'daniel.miklos@simonyi.bme.hu',
      pictureUrl: '/img/DMIKI_1N1PHTBF487G0.webp',
      priority: 1,
    },
    {
      name: 'Telek Benjámin',
      rank: 'előadói csapatvezető',
      emailAddress: 'telek.benjamin@simonyi.bme.hu',
      pictureUrl: '/img/BENI_107HEN1GSLQP0.webp',
      priority: 1,
    },
    {
      name: 'Iván András',
      rank: 'gazdasági felelős',
      emailAddress: 'ivan.andras@simonyi.bme.hu',
      pictureUrl: '/img/_1OHHH5ANP2OH4.webp',
      priority: 1,
    },
    {
      name: 'Bondár Balázs',
      rank: 'expófelelős',
      emailAddress: 'bondar.balazs@simonyi.bme.hu',
      pictureUrl: '/img/BAZSI_Z9YQZJ9QN4X.webp',
      priority: 1,
    },
    {
      name: 'Vizhányó Miklós',
      rank: 'expófelelős',
      emailAddress: 'vizhanyo.miklos.ferenc@simonyi.bme.hu',
      pictureUrl: '/img/VMIKI_1TE9GADS6CUZ8.webp',
      priority: 1,
    },
    {
      name: 'Zámolyi Csaba',
      rank: 'helyszínfelelős',
      emailAddress: 'zamolyi.csaba@simonyi.bme.hu',
      pictureUrl: '/img/PLACEHOLDER_PHOTO_11FR7D8720N3E.webp',
      priority: 1,
    },
    {
      name: 'Zsizsik Máté',
      rank: 'vezető vállalati kapcsolattartó',
      emailAddress: 'zsizsik.mate.tibor@sch.bme.hu',
      pictureUrl: '/img/MATE_L4516Z2WBFA3.webp',
      priority: 1,
    },
  ],
  presentations: [
    {
      slug: 'kotlin-multiplatform',
      title: 'Kotlin Multiplatform: kódmegosztás pragmatikusan',
      room: 'IB028',
      language: 'hu',
      startTime: '2024-03-19T14:45:00+01:00',
      endTime: '2024-03-19T15:15:00+01:00',
      description:
        'A Kotlin első verzióját 2016-ban adta ki a JetBrains. A nyelv azóta folyamatosan fejlődik, új funkciókkal és eszközökkel bővül, mára már élénk közösséggel és ökoszisztémával rendelkezik.\r\n\r\nBár a Kotlin eredeti célja a JVM alapú szoftverfejlesztés volt – asztali és szerver oldali alkalmazások létrehozása – ezt hamar kinőtte. Pár év alatt meghódította az Android fejlesztést is; a Google először hivatalosan támogatott, később pedig elsődleges nyelvvé tette a saját platformján.\r\n\r\nNapjainkban a növekedés legújabb iránya a Kotlin Multiplatform, amivel kitörhetünk a JVM-ről, és szabadon megoszthatunk Kotlin kódot különböző mobil platformok, valamint asztali, webes és szerveroldali alkalmazások között. Ebben az előadásban ennek a technológiának az előnyeivel és legújabb fejleményeivel fogunk megismerkedni.',
      videoUrl: 'https://www.youtube.com/embed/C0UFL3714UE?si=XN_4ZVRXShoC-8mK',
      presenter: {
        name: 'Braun Márton',
        rank: 'Developer Advocate, JetBrains',
        pictureUrl: '/img/BMARTON_CTEAHPBZ8A47.webp',
      },
    },
    {
      slug: 'a-jo-munkasember',
      title: 'IBM WatsonX.ai, a jó munkásember',
      room: 'IB025',
      language: 'hu',
      startTime: '2024-03-19T14:45:00+01:00',
      endTime: '2024-03-19T15:15:00+01:00',
      description:
        'A generatív AI egy erőteljesen fejlődő, természetes nyelven írt szövegek elemzésén alapuló megoldás, mely nagy érdeklődésre tart számot az egész világon. Mivel azonban a technológia – a szükséges számítási kapacitás, és a megfelelő gyakorlati megvalósítási módszerek korábbi elérhetetlensége miatt – csak a közelmúltban vált közismertté, még nem létezik széles körben elfogadott iparági ajánlás arra vonatkozóan, hogy az milyen üzleti problémák megoldására alkalmazható hatékonyan.\r\n\r\nAz előadás során – a Barré által egyéb, konvencionális IBM termékek segítségével kiszolgált iparági, nagyvállalati környezet rövid bemutatása mellett – egy élő demo formájában bemutatásra kerül egy jó eredményekkel kecsegtető lehetséges alkalmazási terület: a nagyvállalati dokumentumtárakban nagy mennyiségben elhelyezkedő, nem indexált dokumentumok utólagos klasszifikálása, és taxonómiai besorolásuknak megfelelő metaadataik kinyerése. Ezt követően bemutatásra kerül, hogy meglátásunk szerint mire potenciálisan jó, és mire biztosan nem jó a technológia, mely felvetésként a kérdés-felelet szekcióban akár vitaindítóként is szolgálhat.',
      videoUrl: 'https://www.youtube.com/embed/IiI9a0YvFp4?si=NJTAuEcuAktlMUS3',
      presenter: {
        name: 'Bartha Tamás Árpád',
        rank: 'vezérigazgató',
        pictureUrl: '/img/BTAMAS_RA3PN517DCTO.webp',
        company: {
          name: 'Barré Technologies',
          logoUrl: '/img/BARRE_176COXBUV467Q.svg',
          url: 'https://www.barre.hu/',
          category: SponsorCategory.FEATURED_SPONSOR,
        },
      },
    },
    {
      slug: 'dronok-harca',
      title: 'Drónok harca: Küzdelem a veszélyes, rosszindulatú drónhasználat ellen',
      room: 'IB028',
      language: 'hu',
      startTime: '2024-03-19T17:30:00+01:00',
      endTime: '2024-03-19T18:00:00+01:00',
      description:
        'Napjainkban már szinte mindenki kapcsolatba került valamilyen formában a drónokkal, amelyek egyre nagyobb tudással és egyre olcsóbban hozzáférhetők. Ezek a – rendkívül sok célra remekül használható – eszközök felelőtlen, vagy rosszindulatú használat esetén nagy veszélyt, jelentős károkat, sőt katasztrófát okozhatnak. Az előadás az ilyen irányú kockázatokról, azok minimalizálását célzó fejlesztési irányokról, lehetőségekről és megoldásokról ad egy áttekintést. Érinti a - rendkívül költséges – felderítés, detektálás, valamint az elhárítási lehetőségek kérdéskörét. Természetesen szó lesz a drónok felhasználása következtében kialakult „aszimmetrikus hadviselésről”, a drónok szerepéről az orosz-ukrán háborúban, valamint az izraeli konfliktusban is. A nemzetközi kitekintést követően, az előadás befejező része bemutatja a témakör hazai vonatkozásait is.',
      videoUrl: 'https://www.youtube.com/embed/MpD9IkwIlA8?si=9to_MRg8mucJK8nJ',
      presenter: {
        name: 'Dr. Kazi Károly',
        rank: 'BHE ügyvezető, MELT elnök',
        pictureUrl: '/img/KKAROLY_DC302KB3P3WL.webp',
      },
    },
    {
      slug: 'arm-sorozatprogramozo',
      title: 'Egy ARM sorozatprogramozó anatómiája',
      room: 'IB025',
      language: 'hu',
      startTime: '2024-03-19T13:30:00+01:00',
      endTime: '2024-03-19T14:00:00+01:00',
      description:
        'Beágyazott rendszerek sorozatgyártásánál hasznos eszköz a sorozatprogramozó, amely gombnyomásra, az USB-s eszközöknél lényegesen gyorsabban képes betölteni a firmware-t a készülékbe. A piacon kapható ARM sorozatprogramozók csak bizonyos típusokat támogatnak, ráadásul a hobbisták számára nem elérhető árúak. Az előadáson részt vevők betekintést nyerhetnek az ARM mikrovezérlők debug interfészébe, megismerkedhetnek az ARM Cortex architektúra és a CMSIS keretrendszer releváns részeivel, valamint a flash memória programozásának részleteivel, kiemelt figyelmet fordítva a gyártófüggetlen megvalósításra. A hardver és a szoftver implementációja egy, a Schönherz Elektronikai Műhelyben fejlesztett ARM sorozatprogramozó példáján kerül bemutatásra.',
      videoUrl: 'https://www.youtube.com/embed/MuUlXWBcsxU?si=KQ7g5lvJBOScdtgL',
      presenter: {
        name: 'Horváth Kristóf',
        rank: 'öregtag, Schönherz Elektronikai Műhely',
        pictureUrl: '/img/HKRISTOF_AAWJB7M93966.webp',
      },
    },
    {
      slug: 'crysys-tresorit',
      title: 'Hogyan lehet eladni a diplomamunkát 150 országban – CrySys laborból indult Tresorit tapasztalatok',
      room: 'IB028',
      language: 'hu',
      startTime: '2024-03-19T15:45:00+01:00',
      endTime: '2024-03-19T16:15:00+01:00',
      description:
        'A Tresoritot BMEs és 1 Corvinusos hallgatók alapították, melynek alapja egy közös kutatási munka volt, és egyikük (az előadó) diplomamunkája is. Korán jelentős tőkét vontak be: már a BSc diplomaosztóra 380M Ft tőkebevonást zártak. De a sikerhez nem vezetett kikövezett út, az első tőkebevonás után rengeteg nehézséggel szembesültek. Fontos a marketing – de mi az? Növekedni kell – de hogyan? Céget és csapatot kell építeni – de ki fog akkor a termékfejlesztéssel foglalkozni? Ma már nagyvállalatok, kormányzati szervek, kisebb-nagyobb cégek világszerte használják a Tresoritot a legbizalmasabb dokumentumok tárolására – de az idevezető út sokszor meglepő fordulatot vett.',
      videoUrl: 'https://www.youtube.com/embed/PCI4OizUHMM?si=jrNKg01UPuVn0usn',
      presenter: {
        name: 'Lám István',
        rank: 'Co-Founder, Board Member & Corporate Development Director, Tresorit',
        pictureUrl: '/img/LISTVAN_1G03WBGQTX4KT.webp',
      },
    },
    {
      slug: 'taming-monsters-karban',
      title: 'Taming Monsters With Dragons or How to Build Digital Twins The Right Way - Part 1',
      room: 'IB025',
      language: 'en',
      startTime: '2024-03-19T16:30:00+01:00',
      endTime: '2024-03-19T17:00:00+01:00',
      description:
        "In the presentation \"Taming Monsters With Dragons or How to Build Digital Twins The Right Way\", Robert Karban, an internationally recognized Systems Engineering Expert with experience at NASA JPL, and Istvan Rath, CEO of IncQuery, will talk about the critical role of systems engineering in contemporary industries like aerospace, automotive, and biomedical. As the complexity of systems increases, so do the stakes in ensuring their functionality and reliability, demanding innovative engineering approaches for their development and operation.\r\n\r\nThe duo will discuss the challenges in the current engineering paradigm, especially the trend towards distributed teamwork. This dispersion often leads to organizational silos, creating barriers to collaboration and innovation and posing risks to project success. This necessitates novel engineering approaches, incorporating advanced processes, engineering eco-systems, and data management strategies.\r\n\r\nA central theme of the presentation is the concept of 'Digital Twins' and 'Digital Threads'. These innovative approaches enable the meaningful connection of people and their work, breaking down silos and fostering collaboration. The presentation aims to inspire future engineers to embrace these cutting-edge techniques for impactful and life-saving advancements.\r\n\r\nSpeaker Robert Karban's presentation is the prequel of Dr. Ráth's presentation on the same topic.",
      videoUrl: 'https://www.youtube.com/embed/bk_D2cILzt4?si=poT7KBuQXHPU9HlP',
      presenter: {
        name: 'Robert Karban',
        rank: 'Principal Systems Engineer',
        pictureUrl: '/img/RKARBAN_NJDMWLBEROOF.webp',
      },
    },
    {
      slug: 'icf',
      title: 'Pályakezdés a Bprof program után: Az ICF Tech Hungary fejlesztőinek karrierútjai',
      room: 'IB028',
      language: 'hu',
      startTime: '2024-03-19T16:30:00+01:00',
      endTime: '2024-03-19T17:00:00+01:00',
      description:
        'Örömmel várjuk az érdeklődőket az ICF Tech Hungary kerekasztal beszélgetésén, ahol vezetőink és vezető fejlesztőink, valamint korábbi Bprof kooperatív képzésben részt vevő kollégáink osztják meg veletek tapasztalataikat az egyetemi éveket követő karrier útjaikról. Lehetőségetek lesz megismerni egy vállalat dinamikus növekedését, belekóstolhattok a mindennapi projektmunkákba, valamint feltárjuk, hogy milyen lehetőségek várnak rátok az egyetem elvégzését követően a munkaerőpiacon. Beszélgetünk majd a karrier lehetőségekről, a célkitűzés és a csapatmunka fontosságáról, valamint  a fejlődési lehetőségekről a szakmában. A kerekasztalt élő “kérdezz-felelek”-el zárjuk, ahol Ti is feltehetitek a kérdéseiteket.',
      videoUrl: 'https://www.youtube.com/embed/AumoSDJ1UlU?si=MmxY4xHWosb-NDP-',
      presenter: {
        name: 'ICF Tech Hungary',
        rank: '',
        pictureUrl: '/img/ICF_1JMW5SNSSLW2R.webp',
        company: {
          name: 'ICF Tech',
          logoUrl: '/img/ICF_ZNY49IVDX4WM.svg',
          url: 'https://careers.icftech.hu/',
          category: SponsorCategory.FEATURED_SPONSOR,
        },
      },
    },
    {
      slug: 'taming-monsters-rath',
      title: 'Taming Monsters With Dragons or How to Build Digital Twins The Right Way - Part 2',
      room: 'IB025',
      language: 'en',
      startTime: '2024-03-19T17:00:00+01:00',
      endTime: '2024-03-19T17:30:00+01:00',
      description:
        "In the presentation \"Taming Monsters With Dragons or How to Build Digital Twins The Right Way\", Robert Karban, an internationally recognized Systems Engineering Expert with experience at NASA JPL, and Istvan Rath, CEO of IncQuery, will talk about the critical role of systems engineering in contemporary industries like aerospace, automotive, and biomedical. As the complexity of systems increases, so do the stakes in ensuring their functionality and reliability, demanding innovative engineering approaches for their development and operation.\r\n\r\nThe duo will discuss the challenges in the current engineering paradigm, especially the trend towards distributed teamwork. This dispersion often leads to organizational silos, creating barriers to collaboration and innovation and posing risks to project success. This necessitates novel engineering approaches, incorporating advanced processes, engineering eco-systems, and data management strategies.\r\n\r\nA central theme of the presentation is the concept of 'Digital Twins' and 'Digital Threads'. These innovative approaches enable the meaningful connection of people and their work, breaking down silos and fostering collaboration. The presentation aims to inspire future engineers to embrace these cutting-edge techniques for impactful and life-saving advancements.\r\n\r\nDr. Ráth's presentation is the sequel of Speaker Robert Karban's presentation on the same topic.",
      videoUrl: 'https://www.youtube.com/embed/bk_D2cILzt4?si=qVXoKp0duLBkigmr&amp;start=1563',
      presenter: {
        name: 'Dr. Ráth István',
        rank: 'CEO, IncQuery',
        pictureUrl: '/img/RISTVAN_1SAOT4AAFFABT.webp',
      },
    },
    {
      slug: 'mese-4tb-diszk',
      title: 'Mese a 4 TB-os diszkről: Egy incidenskezelési történet',
      room: 'IB025',
      language: 'hu',
      startTime: '2024-03-19T15:15:00+01:00',
      endTime: '2024-03-19T15:45:00+01:00',
      description:
        'Mi történhet, ha egy ransomware támadás éri egy gyár belső infrastruktúráját? Milyen hibákat követhetünk el? Mit tehetünk, hogy elkerüljük a hasonló eseteket? Hogyan működik egy modern ransomware infrastruktúra? Milyen egy profin megírt titkosító algoritmus? Milyen lehetőségeink vannak adatok visszaállítására egy támadás után? Többek között ezekre a kérdésekre keressük a választ az előadás során, miközben egy valós incidenskezelési történetet tekintünk át az elmúlt évekből. Ezenkívül megpróbáljuk lefuttatni a támadók által használt ransomware mintát egy szeparált, virtualizált környezetben. Az előadás tanulságokkal szolgál otthoni felhasználóknak és céges környezetben dolgozóknak egyaránt.',
      videoUrl: 'https://www.youtube.com/embed/DGykIKTaoeI?si=bLpXbeQyy7_8Q5nN',
      presenter: {
        name: 'Tamás Kristóf',
        rank: 'Head of Security Services, Ukatemi Technologies',
        pictureUrl: '/img/TKRISTOF_ZJPPBAQL8I47.webp',
      },
    },
    {
      slug: 'ai-biologiaban',
      title: 'AI a molekuláris biológiában',
      room: 'IB025',
      language: 'hu',
      startTime: '2024-03-19T18:45:00+01:00',
      endTime: '2024-03-19T19:15:00+01:00',
      description:
        'A molekuláris biológia területe hatalmas lépésekkel fejlődött az elmúlt évtizedekben. A Human Genome Project által 2003-ra megismerhettük az emberi DNS szekvenciáját. Ma már több génterápiás gyógyszer is elérhető, mint például a 2019-ben gerinc eredetű izomsorvadás kezelésére engedélyezett Zolgensma. Az új mérési módszerek mélyebb betekintést adnak a sejtek viselkedésébe, mint eddig bármikor. A next generation sequencing elterjedésével a DNS-ben tárolt információ megismerésének költsége exponenciálisnál is gyorsabban csökkent. Azonban a rengeteg rendelkezésre álló adat egyelőre kevés áttöréshez vezetett olyan bonyolult betegségek kezelésében, mint a rák vagy a gyulladásos bélbetegségek. Az elmúlt évtized AI forradalmai után adja magát a lehetőség, hogy használjunk a nagymennyiségű rendelkezésre álló adat megértéséhez mesterséges intelligenciát. Viszont a biológiai adatok feldolgozása egyedi kihívásokkal jár. A mérések jellemzően zajosak, hiányzó értékekkel terheltek, az adatkészletek nem egységesek. Az előadásban egy AI fejlesztő szempontjából ismerkedünk meg a rendelkezésre álló adatokkal és, hogy hogyan lehet megküzdeni ezekkel a kihívásokkal.',
      videoUrl: 'https://www.youtube.com/embed/KP4wSDSyQOg?si=y2BaskxRrMQuae05',
      presenter: {
        name: 'Mérő László',
        rank: 'Research Team Lead, Turbine',
        pictureUrl: '/img/MLASZLO_1JCZ9N5AA5EOK.webp',
      },
    },
    {
      slug: 'iot-az-urben',
      title: 'IoT az űrben - de tényleg?',
      room: 'IB028',
      language: 'hu',
      startTime: '2024-03-19T15:15:00+01:00',
      endTime: '2024-03-19T15:45:00+01:00',
      description:
        'Na tessék! Megint ez a buzzword! Igen, tudjuk, a Tárgyak Internete rohamosan nő, gombamód szaporodnak az ipari és otthoni rádiós eszközök. Alapos töprengést igényelne, ha megpróbálnánk összeszámolni, hány olyan elektronikus eszközzel találkozunk naponta, amely valamilyen módon kommunikál a külvilággal. Ma már nehezen tudjuk elképzelni a mindennapjainkat mobiltelefon nélkül, és rövidesen ugyanezt mondhatjuk majd az okos eszközökre is. Tavaly még arról beszéltünk, hogy az okosvárosok építése megkezdődött, most pedig azt halljuk, hogy már a világűrbe is kilóg az IoT. Sőt, a más égitesteken munkát végző robotok, drónok, de akár személyzet számára élet-halál kérdése lehet a köztük és a bázis között lévő állandó kapcsolat.\r\n\r\nMár itt tartunk? De tényleg? De minek? Mi hajtja a légkörön túli terjeszkedést? Tényleg létezik az Űreszközök Internete? Milyen kihívásokkal kell szembenéznie a vállakozó cégeknek a földi körülményekhez képest? Megéri teleszemetelni az Űrt térben, időben és frekvenciatartományban? Az IoT piac egyik meghatározó szereplőjeként ezekre a kérdésekre is megróbálunk választ adni rövid előadásunkban.',
      videoUrl: 'https://www.youtube.com/embed/XzU3ywusz7k?si=ew8v1c_ZHtUWFs5a',
      presenter: {
        name: 'Cseh Ádám',
        rank: 'Applications Engineering Manager',
        pictureUrl: '/img/CSADAM_1IY0U0FCROK06.webp',
        company: {
          name: 'Silicon Labs',
          logoUrl: '/img/SL_Y5X1DBHXY670.svg',
          url: 'https://www.silabs.com/about-us/careers?p=jobs&nl=1',
          category: SponsorCategory.FEATURED_SPONSOR,
        },
      },
    },
    {
      slug: 'vue',
      title: 'Inter(re)active programozás Vue.js-ben',
      room: 'IB025',
      language: 'hu',
      startTime: '2024-03-19T14:00:00+01:00',
      endTime: '2024-03-19T14:30:00+01:00',
      description:
        'A Vue.js az egyik legnépszerűbb webes keretrendszer, mely a reaktív programozási paradigmát valósítja meg, és korábban soha nem látott lehetőségeket biztosít. Nem véletlen, hogy olyan nagyvállalatok döntöttek a használata mellett, mint a Google, a Facebook vagy a Netflix. A Magyarországon is tevékenykedő, Péterffy Tamás által alapított Interactive Brokers technológiai palettájának is a része.\r\n\r\nEbben az előadásban megnézzük, hogy mit is jelent pontosan a reaktív programozási paradigma, és milyen következményei vannak. Utána magát a Vue.js keretrendszert vesszük górcső alá. Az olyan kapcsolódó technológiákról is lesz szó, mint a Pug HTML sablonkönyvtár vagy a Less CSS kiterjesztés.\r\n\r\nAz előadás egyrészt azoknak ajánlott, akik a már jól ismert procedurális, objektumorientált és funkcionális programozási paradigmák mellett egy újabb feltörekvővel, a reaktív paradigmával is meg szeretnének ismerkedni, másrészt mindenkinek, akiket érdekel a webes fejlesztés, és látni szeretnék, hogy mi van a HTML-CSS-JavaScript bűvkörén túl.',
      videoUrl: 'https://www.youtube.com/embed/d81jy3cDIME?si=d-HzRPfdO51NEBIk',
      presenter: {
        name: 'Dr. Faragó Csaba',
        rank: 'Senior Software Developer',
        pictureUrl: '/img/FCSABA_1CQLYYGH834LQ.webp',
        company: {
          name: 'Interactive Brokers',
          logoUrl: '/img/IB_W4TUT1GY25YU.svg',
          url: 'https://www.interactivebrokers.hu/hu/home.php',
          category: SponsorCategory.FEATURED_SPONSOR,
        },
      },
    },
    {
      slug: 'ai-kibertamadas',
      title: 'AI által támogatott kibertámadások jelene és jövője',
      room: 'IB025',
      language: 'hu',
      startTime: '2024-03-19T17:30:00+01:00',
      endTime: '2024-03-19T18:00:00+01:00',
      description:
        '2023 a mesterséges intelligencia éve volt, valószínűleg 2024-ben csillapodik a hype a technológia körül és felszínre kerülnek azok a valós életben is használható megoldások, amik valóban értéket termelnek a magánszemélyek és a vállalkozások számára. Emellett viszont az utóbbi időben egyre többet olvashatunk, hallhatunk a mesterséges intelligencia kiberbiztonságra gyakorolt hatásáról, és arról, hogy hogyan fogja megváltoztatni azt a közeli vagy távoli jövőben. Az előadás célja, hogy átlássunk a média keltette zajon, vegyük sorra milyen támadásokkal találkozunk jelenleg és mi várhat ránk a következő hónapokban.',
      videoUrl: 'https://www.youtube.com/embed/nj9-ZZlgt2Y?si=MokHRFo7zcdz5fTU',
      presenter: {
        name: 'Béres Péter',
        rank: 'IT-vezető',
        pictureUrl: '/img/BPETER_ST29G3U9PJQ5.webp',
        company: {
          name: 'Sicontact',
          logoUrl: '/img/SICONTACT_15M63HYJWCCDV.svg',
          url: 'https://www.eset.com/hu/',
          category: SponsorCategory.FEATURED_SPONSOR,
        },
      },
    },
    {
      slug: 'ai-urhajo-tervezes',
      title: 'Tud-e az AI űrhajót tervezni?',
      room: 'IB028',
      language: 'hu',
      startTime: '2024-03-19T13:00:00+01:00',
      endTime: '2024-03-19T14:00:00+01:00',
      description:
        'Nemrég berobbant a köztudatba a generatív AI lehetősége, számos példát láttunk mesterségesen generált képekre, szövegekre. Vajon komplex feladatok elvégzésére is képes lehet-e ez a technológia, és át fogja venni a fejlesztők munkáját?\r\n\r\nRöviden megnézzük, hogyan működnek, és mit tudnak ezek a modellek, merre halad a technológia. Az űrhajótervezés példáján keresztül áttekintjük egy komplex fejlesztési folyamat kihívásait, a megbízható termékfejlesztési módszertan alapjait. Megnézzük, melyek azok a lépések, ahol a mérnökeink munkáját akár a gépek is elvégezhetnék, illetve hol kell továbbra is az emberi kreativitás és hozzáértés. Ennek fényében meglátjuk, mik azok a mérnöki készségek, amik az AI korában is megtartják értéküket.',
      videoUrl: 'https://www.youtube.com/embed/R27sm-vg-q8?si=t-UoIVlUUIw4Ln9e',
      presenter: {
        name: 'Dr. Csilling Ákos',
        rank: 'Bosch Scientist',
        pictureUrl: '/img/CSAKOS_1N7AYITILCKEK.webp',
        company: {
          name: 'Bosch',
          logoUrl: '/img/BOSCHNOTEXT_1R741C5F9QCN3.svg',
          url: 'https://www.bosch.hu/karrier/?gad_source=1',
          category: SponsorCategory.MAIN_SPONSOR,
        },
      },
    },
    {
      slug: 'vizszimatolas-a-holdon',
      title: 'Vízszimatolás a Holdon',
      room: 'IB028',
      language: 'hu',
      startTime: '2024-03-19T14:00:00+01:00',
      endTime: '2024-03-19T14:30:00+01:00',
      description:
        'A holdi víz az egyik legértékesebb nyersanyag lehet a közeli jövőben, amely fontos szerepet játszhat a jövőbeli küldetéseknél, a holdi tartós emberi jelenlét támogatásában és a földi gazdaság fejlesztésében is. Ezért elengedhetetlen, hogy lehetséges előfordulását és minőségét, hasonlóan több más lehetséges erőforráshoz, karakterizáljuk és feltérképezzük.\r\n\r\nA kozmikus háttérsugárzás folyamatosan bombázza a Hold felszínét, ennek hatására másodlagos neutronsugárzás lép ki a holdfelszínből. Ezt remekül lehet a regolit (holdi talaj) felszín alatti összetételének meghatározására használni mintegy 1 méter mélységig, különös tekintettel annak hidrogén (és így vízjég) tartalmára.\r\n\r\nKorábbi, Hold körüli pályáról végzett neutronspektroszkópiai mérések után 2024-ben kerül sor a tervek szerint az első részletes holdfelszíni mérésekre. A NASA holdi kereskedelmi szállítási programja (Commercial Lunar Payload Services, CLPS) keretében a VIPER holdjáró (Volatiles Investigating Polar Exploration Rover) az Astrobotic cég Griffin leszállóegységén indulhat útnak a Hold felé, míg az Intutive Machines cég az IM-2 küldetésen a NASA első jégbányászati kísérletét (PRIME-1, Polar Resources Ice-Mining Experiment) szállítja a Hold déli sarkvidékére. Az IM-2 küldetése magyar szempontból is fontos, két hazai fejlesztésű neutrondetektor („Vízszimatoló”) is a fedélzeten van.',
      videoUrl: 'https://www.youtube.com/embed/aY4z6uOOHMw?si=x-we9R4Y6kWQmehA',
      presenter: {
        name: 'Hazadi Mátyás, Dr. Pacher Tibor',
        rank: 'villamosmérnöki vezető, ügyvezető igazgató, Puli Space Technologies',
        pictureUrl: '/img/PULI_PRES_IMAGEWEBP_5UKURLPJRZ3P.webp',
      },
    },
    {
      slug: 'duck-db',
      title: 'DuckDB: Egy modern hordozható adatbázis-kezelő rendszer',
      room: 'IB025',
      language: 'hu',
      startTime: '2024-03-19T13:00:00+01:00',
      endTime: '2024-03-19T13:30:00+01:00',
      description:
        'A DuckDB egy új nyílt forráskódú adatbázis-kezelő rendszer, melynek fő fókusza az analitikus lekérdezések hatékony támogatása. Míg a legtöbb hasonló rendszer az “alkalmazás kliens – adatbázis szerver” architektúrát követi, a DuckDB a kliens alkalmazásba beágyazottan (in-process) működik, külső függőségek nélkül. Így a rendszer rendkívül hordozható és könnyen telepíthető a legtöbb népszerű hardver környezetben és operációs rendszerben.\r\n\r\nA DuckDB egy modern SQL adatbázis-kezelő, ami teljes egészében C++11-ben íródott, oszlop alapú adattárolást használ és a lekérdezőmotorja a hatékony vektorizált futtatási módot alkalmazza. Ennek köszönhetően a rendszer gyors és jól skálázódik.\r\n\r\nA DuckDB-t az elmúlt években sikerrel használták különféle rendszerek kiváltására, beleértve dataframe függvénykönyvtárakat (pandas, polars, dplyr), beágyazott adatbázisokat (SQLite), elosztott adatfeldolgozó rendszereket (Spark, Dask) és felhőalapú adattárházakat (Snowflake, Google BigQuery).\r\n\r\nAz előadásban bemutatom a DuckDB fő tervezési irányelveit, a hatékony tárolástól kezdve a párhuzamosítást lehetővé tevő megoldásokig.',
      videoUrl: 'https://www.youtube.com/embed/b4enSPbyIkk?si=F2DegbJucIRVFlt8',
      presenter: {
        name: 'Dr. Szárnyas Gábor',
        rank: 'Developer Relations Advocate, DuckDB',
        pictureUrl: '/img/SZGABOR_LG8FNB91PW4S.webp',
      },
    },
    {
      slug: 'koordinata-rendszer',
      title: 'Koordináta-rendszerek a videójátékokban',
      room: 'IB028',
      language: 'hu',
      startTime: '2024-03-19T18:45:00+01:00',
      endTime: '2024-03-19T19:15:00+01:00',
      description:
        'Videójáték programozói pályafutásom során számtalanszor találkoztam különböző koordináta-rendszerekből adódó problémákkal. Ezek elkerülése végett összegyűjtöttem a legfontosabbnak vélt irányelveket a témában, amelyekkel útmutatást szeretnék nyújtani a kezdő fejlesztők számára. Bemutatom, hogy a projekteknél használt eszközök miként kompatibilisek egymással, és az egyes alrendszereknél milyen egyedi igények vannak, valamint néhány példán keresztül sorba veszem azokat a szempontokat, amiket érdemes figyelembe venni már a játékprogram tervezésénél is.',
      videoUrl: 'https://www.youtube.com/embed/1dbSV2Sm3Lo?si=xGBiwo2qD7MkJEzo',
      presenter: {
        name: 'Nagy Róbert',
        rank: 'Veterán game engine fejlesztő, Gaijin Entertainment',
        pictureUrl: '/img/NROBERT_1MHQVK82HO88I.webp',
      },
    },
    {
      slug: 'ai-llm-otp',
      title: 'AI-LLM megoldások az OTP-nél',
      room: 'IB025',
      language: 'hu',
      startTime: '2024-03-19T18:15:00+01:00',
      endTime: '2024-03-19T18:45:00+01:00',
      description:
        'Az előadás elején piaci kitekintést szeretnék adni arról, hogy milyen dinamikák tapasztalhatóak a nagy nyelvi modellek terén. Ezen kívül be fogom mutatni, hogy mi milyen belső fejlesztéseken dolgozunk, milyen alkalmazási területet látunk a mesterséges intelligencia nagy nyelvi modelljének (AI LLM) felhasználásra. A prezentáció második felében kitérek arra, hogy hogyan fejlesztjük a chat képességünket, belső tudástárainkat annak érdekében, hogy az AI segítségével támogatni tudjuk a banki tevékenységekhez kapcsolódó műveletek egyszerűbbé, automatizáltabbá tételét. Az előadás végén szó lesz arról is, hogy mi hogyan képzeljük el a banknál az AI nagy nyelvi modelljének felhasználását a jövőben és milyen lehetőségeket látunk a belső fejlesztéseink és a piacról beszerezhető tudás ötvözésének.',
      videoUrl: 'https://www.youtube.com/embed/ziSHaEOwEQs?si=SuX6REXZQy_YQSf5',
      presenter: {
        name: 'Szentmihályi Kristóf',
        rank: 'Data Science szakértő',
        pictureUrl: '/img/SZKRISTOF_1ORWDG1G1KO46.webp',
        company: {
          name: 'OTP Bank',
          logoUrl: '/img/OTP_RI4G0842GB45.svg',
          url: 'https://www.otpbank.hu/',
          category: SponsorCategory.FEATURED_SPONSOR,
        },
      },
    },
    {
      slug: 'halozatok',
      title: 'Hálózat jelentkezz! Itt a földi irányítás!  -  Hálózatok, melyek értik az emberi nyelvet.',
      room: 'IB028',
      language: 'hu',
      startTime: '2024-03-19T17:00:00+01:00',
      endTime: '2024-03-19T17:30:00+01:00',
      description:
        'Az előadás egy olyan világba invitál, ahol csak azt kell megfogalmazni, hogy "mit" szeretnénk, a "hogyan"-t pedig rábízhatjuk arra, ami ehhez a legjobban ért: magára a hálózatra. Mindez már nem csak sci-fi, a bemutatott rendszer képes emberi nyelven megfogalmazott igényeket értelmezni és ez alapján önállóan létre is hozni a kívánt szolgáltatást vagy végrehajtani a szükséges változtatásokat egy valódi 5G hálózatban.',
      videoUrl: 'https://www.youtube.com/embed/-q-I74C3BkU?si=Rax69BVmWp4fSRgG',
      presenter: {
        name: 'Nováczki Szabolcs',
        rank: 'Szenior Kutatómérnök',
        pictureUrl: '/img/NSZABOLCS_1AHAIA2A5Z58X.webp',
        company: {
          name: 'Nokia',
          logoUrl: '/img/NOKIA_168XXPH2NWTJG.svg',
          url: 'https://www.facebook.com/nokiahungary/',
          category: SponsorCategory.FEATURED_SPONSOR,
        },
      },
    },
    {
      slug: 'muholdfejlesztes',
      title: 'Műholdfejlesztés a Műegyetemen',
      room: 'IB028',
      language: 'hu',
      startTime: '2024-03-19T18:15:00+01:00',
      endTime: '2024-03-19T18:45:00+01:00',
      description:
        'A Műegyetemi műhold fejlesztés még 2007-ben kezdődött a MASAT-1-gyel, amely az első magyar műholdként került a világűrbe. Őt követte további négy társa, úgy mint a SMOG-P, az ATL-1 és a SMOG-1, akik már a PocketQube, vagyis zsebműhold kategóriába tartoztak. Közülük a SMOG-P úttörőként, a világ első működő egy egységnyi PocketQube-ja volt. Legújabb társuk az MRC-100 egy három egység méretű PocketQube, az eddigi legösszetettebb és legbonyolultabb műhold amely egyetemi oktatók és hallgatók által lett fejlesztve a Műegyetemen. A műholdak mind sikeres küldetést tudhatnak maguk mögött, illetve az MRC-100 jelenleg is végzi a feladatát a világűrben. A műholdak fedélzetére került kísérletek között a technológiai demonstrációtól kezdve a Föld körüli térség elektromágneses szennyezettségének feltárásán és akkumulátorok szigetelésének vizsgálatán át, dozimetriai és optikai szenzorokig számtalan kísérlet megtalálható. Az előadásban a fejlesztésről és a kutatási eredményekről kaphat ízelítőt a hallgatóság.',
      videoUrl: 'https://www.youtube.com/embed/_om451-sPB4?si=fesfsBmV-uYj3tZK',
      presenter: {
        name: 'Püspöki Péter',
        rank: 'MSc űrmérnök hallgató, szakkollégista',
        pictureUrl: '/img/PPETER_18PDSN0XJV4JE.webp',
      },
    },
    {
      slug: 'minden-3d',
      title: 'MINDENT 3D-BE!',
      room: 'IB025',
      language: 'hu',
      startTime: '2024-03-19T15:45:00+01:00',
      endTime: '2024-03-19T16:15:00+01:00',
      description:
        'Mézes Mackó, Villányi Kopár, Ferrari, Mi a baj a kutyákkal? „ A királynőt megölni nem kellfélnetek” Blade Runner, Mi van a zsebemben? 1954: 7:1 , Túl az üveghegyen…\r\n\r\nMi köti össze a fent leírtakat és azt a másik harminc talányos szót, fogalmat, kifejezést, mondatot, amit az első dián lát majd a részvevő? Erre ad gyakorlati választ az előadó olymódon, hogy a hallgatóság választásai alapján, helyben szerkeszti és „fűszerezi” mondanivalóját.',
      videoUrl: 'https://www.youtube.com/embed/iA2YgseV3Yg?si=rHnViHSii9WAF8hw',
      presenter: {
        name: 'Fehér András',
        rank: 'Üzletfejlesztési igazgató, Mensor3D',
        pictureUrl: '/img/FEHERA_1NUL6R3D3G48E.webp',
        company: {
          name: '4iG',
          logoUrl: '/img/4IG_TQNCRLDIT5O7.svg',
          url: 'https://4ig.hu/nyito',
          category: SponsorCategory.FEATURED_SPONSOR,
        },
      },
    },
  ],
};
